sudo: required
services:
  - docker
matrix:
  include:
    - stage: Build and Push Texlive 2019 and Pandoc
      # Currently alpine is now working due to chmod issues!
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build ./texlive/2019/ -t nimamahmoudi/texlive-2019:debian
        - docker push nimamahmoudi/texlive-2019:debian
        - docker tag nimamahmoudi/texlive-2019:debian nimamahmoudi/texlive-2019
        - docker push nimamahmoudi/texlive-2019
    - script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build ./pandoc/ -t nimamahmoudi/pandoc
      - docker push nimamahmoudi/pandoc
    - stage: Build Composite Docker Image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build ./latex-parser/ -t nimamahmoudi/latex-parser
        - docker push nimamahmoudi/latex-parser

