sudo: required
services:
  - docker
matrix:
  include:
    - stage: Build and Push Texlive 2019
      # # Currently alpine is now working due to chmod issues!
      # script:
      #   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #   - docker build ./texlive/2019/ -f ./texlive/2019/Dockerfile-alpine -t nimamahmoudi/texlive-2019:alpine
      #   - docker push nimamahmoudi/texlive-2019:alpine
    
    - script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build ./texlive/2019/ -t nimamahmoudi/texlive-2019:debian
      - docker push nimamahmoudi/texlive-2019:debian
