# Currently not working due to chmod issues!!!
FROM alpine

# Original Installation Manager File:
# ftp://tug.org/historic/systems/texlive/2019/install-tl-unx.tar.gz

# Install packages to download TeX live
RUN apk update \
  && apk add perl wget xz \
  && rm -rf /var/cache/apk/*

# Install TeX live
COPY texlive.profile /
RUN wget https://github.com/nimamahmoudi/docker-latex-parser/raw/master/texlive/2019/install-tl-unx.tar.gz \
  && tar xzvf install-tl-unx.tar.gz \
  && ./install-tl-*/install-tl -profile texlive.profile \
  && rm -rf install-tl-* \
  && rm texlive.profile

ENV PATH="/usr/local/texlive/2019/bin/x86_64-linux:${PATH}"
